apiVersion: v1
kind: Service
metadata:
  name: pi-hole
  labels:
    app: pi-hole
spec:
  ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: pi-hole
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  labels:
    app: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      containers:
      - name: pi-hole
        image: pihole/pihole:latest
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
        env:
        - name: TZ
          value: "America/New_York"
        - name: WEBPASSWORD
          value: "foobar"
        - name: VIRTUAL_HOST
          value: "pihole.local"
        - name: DNS1
          value: "1.1.1.1" 